version: "3.3"
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    networks:
      - docker_cav-mysql
networks:
  docker_cav-mysql:
    external: true
